### ISSUE TITLE
Art hero Small Bug

### ISSUE THREAD

**Issue by Treyway995** [Metagawa/Steam-Deck-Themes#11]
Hey Meta,

So i am really loving your creation with art hero, it's easily one of my favorite UI plugins on deck right now. However there's a small bug right now and it is if you completely remove the footer, and scroll down to you what's new, friends, and recommend tab the plugin actually clips when ever your trying to scroll to see what is going on what your friends progress. I will actually show you because it's easier for me to do that then tell you.

**Comment by Treyway995** [comment]
> Hey Meta,
> 
> So i am really loving your creation with art hero, it's easily one of my favorite UI plugins on deck right now. However there's a small bug right now and it is if you completely remove the footer, and scroll down to you what's new, friends, and recommend tab the plugin actually clips when ever your trying to scroll to see what is going on what your friends progress. I will actually show you because it's easier for me to do that then tell you.

https://user-images.githubusercontent.com/131362759/236685303-80420223-d459-4994-9c3c-1ff455aab05a.MOV

**Comment by Metagawa** [comment]
Yeah that's a weird bug, never use that part of the ui myself so never saw it. I'll look into it the next time I am working on art hero but themes are very low on my list of priorities currently. I wouldn't expect an update on this anytime at all over the next few weeks just so you know.

**Comment by Treyway995** [comment]
Hey Met,

Thanks for the reply, and thanks for acknowledging the bug. And of course
take your time, i just wanted to address it so it can at least be known.
But have a wonderful rest of your day my friend!!!

**Comment by Metagawa** [comment]
Hey, sorry it took so long to get back to this, but I have recently redone art hero entirely, so this bug should be completely gone now.
