### ISSUE TITLE
Images go to bottom right 

### ISSUE THREAD

**Issue by Rhinehart58** [Metagawa/Steam-Deck-Themes#12]
When I don't have expanded hero on the image for each game, it moves to the bottom right, and I can't figure out why. https://imgur.com/a/sMcupb6

**Comment by Metagawa** [comment]
This is due to a recent update valve made I believe. Can't promise any ETA on when or if I'll fix it. I haven't been tinkering with themes in half a year.

**Comment by Metagawa** [comment]
At the very least I won't consider it until after the changes they made are in all branches, non just preview. I'm not going to maintain multiple versions.

**Comment by tuxx** [comment]
Same issue here on the preview channel. Guess i'll have to disable the theme for now, i understand you dont wanna keep updating multiple versions. Was a great theme tho :+1:

**Comment by Metagawa** [comment]
I'm working on an update now that it has hit stable. Keep an eye on deckthemes.
