### ISSUE TITLE
New footer CSS adjustments

### ISSUE THREAD

**Issue by LeLobster** [Metagawa/Steam-Deck-Themes#13]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when themes change the footer.
No, but in all seriousness. I love Art Hero on my deck but since [the new rewrite](https://github.com/Metagawa/Steam-Deck-Themes/commit/6e0c1e3451af288cf211eb69c492211ea1ad272c#diff-333db700c9c24f0ac12dcf3202f0cc97d84314790d2f4af14b1dc5ab2873fe22) AH also changes the footer which I really dislike.  
It's way too thin, the buttons look too small compared to the other UI elements, it no longer is attached to the QAM, and with the theme Clean Game View active the "ACTIVITY, YOUR STUFF, COMMUNITY, GAME INFO" buttons on a game page halfway shine through the footer which looks bad compared to before, especially now that it's see through as well.

**Describe the solution you'd like**
A toggle to switch on/off the adjustment of the footer (including the filters), or removal of the footer rules all together and making this as a separate theme, possibly as dependency in AH which still allows users to disable it like you did with [Game Header Text Stroke](https://github.com/Metagawa/Steam-Deck-Themes/tree/main/Game%20Header%20Text%20Stroke) .

**Describe alternatives you've considered**
I tried changing back to default height via other themes i.e. Delly footer but AH rules kept priority and I was unable to change the footer back to its normal size.  
I also saw you had Minus and Lite but these haven't been updated in months.

**Additional context**
Nothing, just a thank you for AH. I'll keep using it as part of my theme regardless but I really dislike footer adjustments.

**Comment by Metagawa** [comment]
Not possible for the theme to work correctly as intended with the options you're describing until Delly footer dev fixes his theme and it can be a dependency again. Go into shared.css and delete the footer code if it bothers you but the theme won't look correct.

**Comment by Metagawa** [comment]
Also I do not support any other themes than the ones that are dependencies of art hero. So clean game view would not be considered when I make adjustments to art hero. I also won't separate out the footer code into its own extension as that wouls simply make it far too complicated to maintain with art hero needing to work with and without it.

**Comment by LeLobster** [comment]
> Also I do not support any other themes than the ones that are dependencies of art hero. So clean game view would not be considered when I make adjustments to art hero.

Understandable.

> I also won't separate out the footer code into its own extension as that wouls simply make it far too complicated to maintain with art hero needing to work with and without it.

Also understandable.

Sad to hear my request was not feasible, but thanks for your reply nonetheless.
