### ISSUE TITLE
Art hero 16:9 widescreen option not showing anymore

### ISSUE THREAD

**Issue by Pitipitipiti333** [Metagawa/Steam-Deck-Themes#15]
Basically what title says. A couple of updates ago it was present, not the list/row of games in homepage is floating / a little bit lifted from the bottom of the screen :)

**Comment by Metagawa** [comment]
The version on deckthemes has been reverted to an older version. If you want the one with 16:9 support download it manually from here. I won't be updating art hero again until dellyfooter gets updated due to that being a major dependency.
